# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CopyFiles@2
  inputs:
    Contents: 'css/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: CopyFiles@2
  inputs:
    Contents: 'gymschedule.html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'build1'
    publishLocation: 'Container'
- task: Docker@2
  inputs:
    containerRegistry: 'dock1'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'dock1'
    repository: 'udisha2future/dock-test1'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'


